#include "global_var.h"
void Restart(int argc);
double upwind(double argc, double argc2);
double v_r(double argc, double argc2);
double v_t(double argc, double argc2);
double v_pp(double argc, double argc2, int argc3);
double stokes(double argc, double argc2);
void upwind_size(double argc); 
void upwind_ND(double argc);
void diffusion(double argc); 
void grow_two_pop(double argc, double argc2); 
void check();
void init();
double advec_grow(double argc, double argc1, int argc2);

int drift(double argc,double argc2, double argc3);
double drag_group(double argc,double argc2);
double w_K(double argc);
double density(double argc);
double sound_sp(double argc);
double viscosity(double argc);
double mean_path( double argc);
double vr_estimate(double argc1,double argc2,double *argc3);
double drift_vr(double argc1,double argc2,double *argc3);
double drift_vr_test(double argc1,double argc2,double *argc3);
double v_r1_test(double argc1, double argc2);
double *v_r2(double argc1, double argc2);
void Init2();
void frag();
void stokes_size();
void tau_unity();
void grow_1();
void grow_3();
double grow_3b();
double grow_3b2();
double grow_3b2_test();
double grow_3b_ada();
double grow_3b_ada2();
double grow_3b_ada_fix();
void dust_evolve(double argc);
void check_disk(double argc);
void disk_evolve();
double vr_gas(double argc);
double height(double argc);
double coag_kernel(double a_pb1,double a_pb2,double delta_v,double rho1, double rho2, double dt0, double rad, int i, int j, int jj);
void coagulation(double argc1, double argc2);
void fragmentation(double argc1, double argc2);
double p_size_func(double argc);
double Sigma_gas(double argc);
double pressure(double argc);
double k_P_func(double argc);
double yeta(double argc);
double v_K(double argc);
double vt_gas(double argc);
double temperature(double argc);
double func_spline3(double argc1,pSPLINE argc2);
double func_line1(double argc1,pSPLINE argc2);
double opac(double argc1, double argc2);
double opa_iter(double r, double opa0);
double alpha_func(double argc);
void opa_init();
int Spline3(pSPLINE pLine);
int line1(pSPLINE pline);
